project:
  type: website

execute:
  freeze: auto

website:
  title: "Curso de estatística"
  output-dir: docs

  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Início
      - r-stuff.qmd
      - python-stuff.qmd
    right:
      - icon: github
        href: "https://steven.metodosquantitativos.com/"
        aria-label: GitHub

format:
  html:
    theme: superhero
    css: styles.css
    toc: true
